In [1]:
#bfs
def bfs(graph,st):
    visited=[]
    queue=[]
    queue.append(st)
    while(queue!=[]):
        val=queue.pop(0)
        if val not in visited:
            visited.append(val)
            queue=queue+graph[val]
    return visited

if __name__ == '__main__':
    graph={
        0:[1,2],
        1:[0,2,3],
        2:[0,1,4],
        3:[1,4],
        4:[2,3]
    }
    print(f"Blind Search(BFS) Traversal : {bfs(graph,0)}")

Blind Search(BFS) Traversal : [0, 1, 2, 3, 4]


In [2]:
#dfs
def dfs(graph,st):
    visited=[]
    stack=[]
    stack.append(st)
    while(stack!=[]):
        val=stack.pop()
        if val not in visited:
            visited.append(val)
            stack=stack+graph[val]
    return visited

def dfs_Recursion(graph,val,visited):
    if len(visited)==len(graph):
        return
    if val not in visited:
        visited.append(val)
        for point in graph[val]:
            dfs_Recursion(graph,point,visited)

if __name__ == '__main__':
    graph={
        0:[1,2,3],
        1:[0,2],
        2:[0,1,4],
        3:[0],
        4:[2]
    }
    print(f"Blind Search(DFS) Traversal : {dfs(graph,0)}")
    visited=[]
    dfs_Recursion(graph,0,visited)
    print(f"Blind Search(DFS) Traversal using Recursion : {visited}")

Blind Search(DFS) Traversal : [0, 3, 2, 4, 1]


In [3]:
#knapsack
class Item:
    def __init__(self,weight,value):
        self.weight = weight
        self.value = value

def greedyFractionalKnapsack(items,capacity):
    items.sort(key=lambda item: (item.value/item.weight), reverse=True) 
    finalvalue = 0.0
    remaining_capacity = capacity
    for item in items:
        if item.weight <= remaining_capacity:
            remaining_capacity -= item.weight
            finalvalue += item.value
        else:
            finalvalue += item.value * remaining_capacity / item.weight
            break
    return finalvalue

def recursiveKnapsackHelper(items, remaining_capacity):
    if items[0].weight<=remaining_capacity:
        remaining_capacity -= items[0].weight
        return items[0].value + recursiveKnapsackHelper(items[1:], remaining_capacity)
    return items[0].value * remaining_capacity / items[0].weight

def recursiveKnapsack(items,capacity):
        items.sort(key=lambda item: (item.value/item.weight), reverse=True)
        return recursiveKnapsackHelper(items,capacity)
 
 
if __name__ == "__main__":
    no_of_items = 5
    weights=[5,10,15,22,25]
    values=[30,40,45,77,90]
    items = []
    for i in range(no_of_items):
        items.append(Item(weights[i], values[i]))
    capacity = 60

    max_profit = greedyFractionalKnapsack(items,capacity)
    max_profit2 = recursiveKnapsack(items,capacity)
    print(f"Maximum Profit: {max_profit}")
    print(f"Maximum Profit using Recursion: {max_profit2}")

Blind Search(DFS) Traversal using Recursion : [0, 1, 2, 4, 3]


In [1]:
#A*
def heuristic(n):
        H_dist = {
            'A': 10,
            'B': 8,
            'C': 5,
            'D': 7,
            'E': 3,
            'F': 6,
            'G': 5,
            'H': 3,
            'I': 1,
            'J': 0
        }
        return H_dist[n]

def get_neighbors(v):
    if v in Graph:
        return Graph[v]
    else:
        return None

def aStarSearch(start_node, stop_node):
        open_set = set(start_node) 
        closed_set = set()
        g = {} 
        parents = {}
        g[start_node] = 0
        parents[start_node] = start_node
         
        while len(open_set) > 0:
            n = None
            for v in open_set:
                if n == None or g[v] + heuristic(v) < g[n] + heuristic(n):
                    n = v

            if n == stop_node or Graph[n] == None:
                pass
            else:
                for (m, weight) in get_neighbors(n):
                    if m not in open_set and m not in closed_set:
                        open_set.add(m)
                        parents[m] = n
                        g[m] = g[n] + weight
                    else:
                        if g[m] > g[n] + weight:
                            g[m] = g[n] + weight
                            parents[m] = n
                            if m in closed_set:
                                closed_set.remove(m)
                                open_set.add(m)
 
            if n == None:
                print('Path does not exist!')
                return None
            if n == stop_node:
                path = []
                while parents[n] != n:
                    path.append(n)
                    n = parents[n]
                path.append(start_node)
                path.reverse()
                print('Path found: {}'.format(path))
                return path
            open_set.remove(n)
            closed_set.add(n)
 
        print('Path does not exist!')
        return None


if __name__ == '__main__':
    Graph = {
        'A': [('B', 6), ('F', 3)],
        'B': [('A',6),('C', 3),('D', 2)],
        'C': [('B',3),('D',1),('E',5)],
        'D': [('B',2),('C',1),('E', 8)],
        'E': [('C',5),('D', 8),('I',5),('J',5)],
        'F': [('A',3),('G',1),('H',7)],
        'G': [('F',1),('I',3)],
        'H': [('F',7),('I',2)],
        'I': [('E',5),('G',3),('H',2),('J',3)],
        'J': [('E',5),('I',3)]
    }
    aStarSearch('A', 'J')

Path found: ['A', 'F', 'G', 'I', 'J']


In [2]:
#EXP 5
#Write a program in python to implement TSP

import itertools

def tsp(graph, start):
    # Generate all possible permutations of cities to visit
    cities = list(graph.keys())
    cities.remove(start)
    permutations = list(itertools.permutations(cities))
    
    # Calculate the total distance for each permutation
    shortest_distance = float('inf')
    shortest_path = None
    
    for permutation in permutations:
        distance = 0
        current_city = start
        
        for next_city in permutation:
            distance += graph[current_city][next_city]
            current_city = next_city
        
        # Return to the starting city
        distance += graph[current_city][start]
        
        # Update the shortest distance and path if necessary
        if distance < shortest_distance:
            shortest_distance = distance
            shortest_path = permutation + (start,)
    
    return shortest_distance, shortest_path


# Example usage
graph = {
    'A': {'A': 0, 'B': 10, 'C': 15, 'D': 20},
    'B': {'A': 10, 'B': 0, 'C': 35, 'D': 25},
    'C': {'A': 15, 'B': 35, 'C': 0, 'D': 30},
    'D': {'A': 20, 'B': 25, 'C': 30, 'D': 0}
}

start_city = 'A'
distance, path = tsp(graph, start_city)

print("Shortest Distance:", distance)
print("Shortest Path:", path)


Shortest Distance: 80
Shortest Path: ('B', 'D', 'C', 'A')


In [3]:
#water jug
def water_jug_problem(jug1_capacity, jug2_capacity, target_amount):
    # Initial state of the jugs
    jug1 = 0
    jug2 = 0

    # Set of visited states to avoid loops
    visited = set()

    # Queue for BFS
    queue = [(jug1, jug2, [])]

    while queue:
        jug1, jug2, path = queue.pop(0)

        # Check if the target amount is reached
        if jug1 == target_amount or jug2 == target_amount:
            if jug1 == target_amount:
                path.append(f"Fill Jug 1 ({jug1_capacity}L)")
            else:
                path.append(f"Fill Jug 2 ({jug2_capacity}L)")
            return path

        # Generate possible actions
        actions = [
            ("Fill Jug 1", jug1_capacity, jug2),
            ("Fill Jug 2", jug1, jug2_capacity),
            ("Empty Jug 1", 0, jug2),
            ("Empty Jug 2", jug1, 0),
            ("Pour Jug 1 to Jug 2", max(0, jug1 - (jug2_capacity - jug2)), min(jug2 + jug1, jug2_capacity)),
            ("Pour Jug 2 to Jug 1", min(jug1 + jug2, jug1_capacity), max(0, jug2 - (jug1_capacity - jug1)))
        ]

        for action, new_jug1, new_jug2 in actions:
            if (new_jug1, new_jug2) not in visited:
                visited.add((new_jug1, new_jug2))
                queue.append((new_jug1, new_jug2, path + [action]))

    return None

# Example usage
jug1_capacity = 4
jug2_capacity = 3
target_amount = 2

result = water_jug_problem(jug1_capacity, jug2_capacity, target_amount)
if result:
    print("Steps to measure the target amount of water:")
    for step in result:
        print(step)
else:
    print("Cannot measure the target amount of water with the given jug capacities.")


Shortest Distance: 80
Shortest Path: ('B', 'D', 'C', 'A')


In [4]:
#water jug2
from collections import defaultdict
jug1, jug2, aim = 4, 3, 2
visited = defaultdict(lambda: False)
def waterJugSolver(amt1, amt2):
	if (amt1 == aim and amt2 == 0) or (amt2 == aim and amt1 == 0):
		print(amt1, amt2)
		return True
	
	if visited[(amt1, amt2)] == False:
		print(amt1, amt2)
		visited[(amt1, amt2)] = True
		return (waterJugSolver(0, amt2) or
				waterJugSolver(amt1, 0) or
				waterJugSolver(jug1, amt2) or
				waterJugSolver(amt1, jug2) or
				waterJugSolver(amt1 + min(amt2, (jug1-amt1)),
				amt2 - min(amt2, (jug1-amt1))) or
				waterJugSolver(amt1 - min(amt1, (jug2-amt2)),
				amt2 + min(amt1, (jug2-amt2))))
	else:
		return False


print("Steps: ")
waterJugSolver(0, 0)

Steps: 
0 0
4 0
4 3
0 3
3 0
3 3
4 2
0 2


True

In [ ]:
#hangman
import random

# List of words to choose from
word_list = ["apple", "banana", "cherry", "durian", "elderberry", "fig", "grapefruit", "honeydew"]

def hangman():
    # Choose a random word from the word_list
    word = random.choice(word_list)

    # Set up variables
    guessed_letters = []
    tries = 6

    # Loop until the game is over
    while True:
        # Display the current state of the word
        display_word = ""
        for letter in word:
            if letter in guessed_letters:
                display_word += letter + " "
            else:
                display_word += "_ "
        print(display_word)

        # Check if the player has guessed all the letters
        if "_" not in display_word:
            print("Congratulations! You guessed the word correctly!")
            break

        # Get the player's guess
        guess = input("Guess a letter: ").lower()

        # Check if the guess is a single letter
        if len(guess) != 1 or not guess.isalpha():
            print("Please enter a single letter.")
            continue

        # Check if the letter has already been guessed
        if guess in guessed_letters:
            print("You have already guessed that letter.")
            continue

        # Add the guessed letter to the list
        guessed_letters.append(guess)

        # Check if the guessed letter is in the word
        if guess in word:
            print("Good guess!")
        else:
            print("Wrong guess!")
            tries -= 1

        # Check if the player has run out of tries
        if tries == 0:
            print("You have run out of tries. The word was:", word)
            break

        # Display the remaining tries
        print("Tries left:", tries)
        print()

# Start the game
print("Welcome to Hangman!")
hangman()


In [ ]:
# EXP 6
#Solve the 8-puzzle problem using A* search algorithm

from queue import PriorityQueue

# Function to calculate the Manhattan distance heuristic
def calculate_heuristic(state, goal):
    distance = 0
    for i in range(len(state)):
        if state[i] != goal[i]:
            distance += 1
    return distance

# Function to swap tiles in the puzzle
def swap_tiles(state, i, j):
    new_state = list(state)
    new_state[i], new_state[j] = new_state[j], new_state[i]
    return tuple(new_state)

# Function to retrieve the path from the goal state to the start state
def retrieve_path(came_from, start, goal):
    path = [goal]
    while path[-1] != start:
        path.append(came_from[path[-1]])
    path.reverse()
    return path

# A* search algorithm
def solve_8_puzzle(start, goal):
    # Initialize the start node
    open_set = PriorityQueue()
    open_set.put((0, start))
    came_from = {}
    g_score = {start: 0}
    f_score = {start: calculate_heuristic(start, goal)}

    while not open_set.empty():
        current = open_set.get()[1]

        if current == goal:
            return retrieve_path(came_from, start, goal)

        # Generate the neighbors of the current state
        neighbors = []
        zero_index = current.index(0)
        if zero_index - 3 >= 0:
            neighbors.append(swap_tiles(current, zero_index, zero_index - 3))
        if zero_index + 3 < len(current):
            neighbors.append(swap_tiles(current, zero_index, zero_index + 3))
        if zero_index % 3 != 0:
            neighbors.append(swap_tiles(current, zero_index, zero_index - 1))
        if zero_index % 3 != 2:
            neighbors.append(swap_tiles(current, zero_index, zero_index + 1))

        # Process each neighbor
        for neighbor in neighbors:
            tentative_g_score = g_score[current] + 1

            if neighbor not in g_score or tentative_g_score < g_score[neighbor]:
                came_from[neighbor] = current
                g_score[neighbor] = tentative_g_score
                f_score[neighbor] = tentative_g_score + calculate_heuristic(neighbor, goal)
                open_set.put((f_score[neighbor], neighbor))

    # No path found
    return None

# Test the algorithm
start_state = (1, 2, 3, 0, 4, 6, 7, 5, 8)
goal_state = (0, 1, 2, 3, 4, 5, 6, 7, 8)

path = solve_8_puzzle(start_state, goal_state)
if path is None:
    print("No solution found.")
else:
    print("Solution path:")
    for state in path:
        print(state)

        
        """

        The code starts by importing the PriorityQueue class from the queue module.

The calculate_heuristic function is defined to calculate the Manhattan distance heuristic between two states. It counts the number of positions where the current state and the goal state have different values.

The swap_tiles function takes a state, two indices, and swaps the tiles at those indices, returning the new state.

The retrieve_path function takes a dictionary came_from, a start state, and a goal state. It reconstructs the path from the goal state to the start state by following the parent pointers in the came_from dictionary.

The solve_8_puzzle function takes a start state and a goal state. It initializes the open set as a priority queue, came_from as an empty dictionary, g_score as a dictionary with the start state's score initialized to 0, and f_score as a dictionary with the start state's score initialized to the heuristic value.

The algorithm enters a loop that continues until the open set is empty.

Inside the loop, it retrieves the state with the lowest f_score value from the open set.

If the current state is the goal state, the algorithm calls the retrieve_path function to obtain the path from the start state to the goal state and returns it.

If the current state is not the goal state, the algorithm generates the neighbors of the current state by swapping the empty tile with its adjacent tiles.

For each neighbor, it calculates the tentative g_score as the current g_score plus 1.

If the neighbor is not in the g_score dictionary or the tentative g_score is lower than the previous g_score for the neighbor, the algorithm updates the came_from dictionary, g_score, and f_score for the neighbor. It also adds the neighbor to the open set with its f_score as the priority.

After processing all neighbors, the loop continues to the next iteration.

If the open set is empty and the goal state has not been reached, the algorithm returns None to indicate that no solution was found.

An example test case is provided to demonstrate the usage of the algorithm. The start_state represents the initial state of the 8-puzzle, and the goal_state represents the desired goal state.

The solve_8_puzzle function is called with the start_state and goal_state, and the returned path is stored in the path variable.

If a solution path exists (i.e., path is not None), it prints "Solution path:" followed by each state in the path. Otherwise, it prints "No solution found."
        
        """

In [5]:
# Tic-Tac-Toe Program using
# random number in Python

# importing all necessary libraries
import numpy as np
import random
from time import sleep

# Creates an empty board


def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

# Check for empty places on board


def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

# Select a random place for the player


def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)

# Checks whether the player has three
# of their marks in a horizontal row


def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a vertical row


def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a diagonal row


def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

# Evaluates whether there is
# a winner or a tie


def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

# Main function to start the game


def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)


# Driver Code
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 1 0]]
Board after 2 move
[[0 2 0]
 [0 0 0]
 [0 1 0]]
Board after 3 move
[[0 2 0]
 [1 0 0]
 [0 1 0]]
Board after 4 move
[[2 2 0]
 [1 0 0]
 [0 1 0]]
Board after 5 move
[[2 2 0]
 [1 0 1]
 [0 1 0]]
Board after 6 move
[[2 2 0]
 [1 0 1]
 [0 1 2]]
Board after 7 move
[[2 2 0]
 [1 1 1]
 [0 1 2]]
Winner is: 1


In [ ]:
#Nqueens

# Python3 program to solve N Queen
# Problem using backtracking

global N
N = 4


def printSolution(board):
	for i in range(N):
		for j in range(N):
			if board[i][j] == 1:
				print("Q",end=" ")
			else:
				print(".",end=" ")
		print()


# A utility function to check if a queen can
# be placed on board[row][col]. Note that this
# function is called when "col" queens are
# already placed in columns from 0 to col -1.
# So we need to check only left side for
# attacking queens
def isSafe(board, row, col):

	# Check this row on left side
	for i in range(col):
		if board[row][i] == 1:
			return False

	# Check upper diagonal on left side
	for i, j in zip(range(row, -1, -1),
					range(col, -1, -1)):
		if board[i][j] == 1:
			return False

	# Check lower diagonal on left side
	for i, j in zip(range(row, N, 1),
					range(col, -1, -1)):
		if board[i][j] == 1:
			return False

	return True


def solveNQUtil(board, col):

	# Base case: If all queens are placed
	# then return true
	if col >= N:
		return True

	# Consider this column and try placing
	# this queen in all rows one by one
	for i in range(N):

		if isSafe(board, i, col):

			# Place this queen in board[i][col]
			board[i][col] = 1

			# Recur to place rest of the queens
			if solveNQUtil(board, col + 1) == True:
				return True

			# If placing queen in board[i][col
			# doesn't lead to a solution, then
			# queen from board[i][col]
			board[i][col] = 0

	# If the queen can not be placed in any row in
	# this column col then return false
	return False


# This function solves the N Queen problem using
# Backtracking. It mainly uses solveNQUtil() to
# solve the problem. It returns false if queens
# cannot be placed, otherwise return true and
# placement of queens in the form of 1s.
# note that there may be more than one
# solutions, this function prints one of the
# feasible solutions.
def solveNQ():
	board = [[0, 0, 0, 0],
			[0, 0, 0, 0],
			[0, 0, 0, 0],
			[0, 0, 0, 0]]

	if solveNQUtil(board, 0) == False:
		print("Solution does not exist")
		return False

	printSolution(board)
	return True


# Driver Code
if __name__ == '__main__':
	solveNQ()



In [6]:
#Monkey Banana
def monkey_banana_problem(n, m, move_cost, jump_cost):
    # Create a 2D table to store the minimum cost
    dp = [[0] * (m + 1) for _ in range(n + 1)]
    
    # Initialize the first row and column
    for i in range(1, n + 1):
        dp[i][0] = i * move_cost
    for j in range(1, m + 1):
        dp[0][j] = j * jump_cost
    
    # Fill in the rest of the table
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            # Calculate the cost of moving to the current cell
            move_to_current = dp[i - 1][j] + move_cost
            
            # Calculate the cost of jumping to the current cell
            jump_to_current = dp[i][j - 1] + jump_cost
            
            # Take the minimum cost between moving and jumping
            dp[i][j] = min(move_to_current, jump_to_current)
    
    # Return the minimum cost to reach the bananas
    return dp[n][m]

# Example usage
n = 3  # Number of moves
m = 4  # Number of jumps
move_cost = 1  # Cost of moving
jump_cost = 2  # Cost of jumping

min_cost = monkey_banana_problem(n, m, move_cost, jump_cost)
print("Minimum cost to reach the bananas:", min_cost)

Minimum cost to reach the bananas: 11
